name: FamilyBounty
version: '1.0'
main: fr.zeyx.familybounty.FamilyBounty
api-version: 1.17
authors: [ZeyX]
description: Plugin qui ajoute un système de Bounty
commands:
  bounty:
    description: Commande principale pour mettre un bounty
